### ISSUE TITLE
Рассмотреть добавление в проект автоматического тестирования верстки

### ISSUE THREAD

**Issue by ibadin** [prikhodkin/gulp_prikhodkin#15]
По мотивам статьи http://glivera-team.github.io/how-to/2018/12/13/testing-with-screens.html

**Comment by prikhodkin** [comment]
Не считаю 100% пиксель перфект жесткой необходимостью, если сильно хочется, можешь сделать ПР, зарилизим в отдельную ветку для тех кому нужно
