### ISSUE TITLE
Добавить поддержку async/await

### ISSUE THREAD

**Issue by ibadin** [prikhodkin/gulp_prikhodkin#17]
Сейчас если попытаться использовать async/await выдается ошибка в консоли, ставил такие плагины 
@babel/plugin-transform-runtime в dev-dependencies и @babel/runtime в dependencies  с ними работало

**Comment by prikhodkin** [comment]
Кинь PR

**Comment by prikhodkin** [comment]
Готово https://github.com/prikhodkin/gulp_prikhodkin/releases/tag/v.5.0
